### ISSUE TITLE
CE labels always zero?

### ISSUE THREAD

**Issue by alexandres** [DI4IR/SIGIR2021#13]
Hi!

I was looking through the training code and found this a bit strange: https://github.com/DI4IR/SIGIR2021/blob/main/src/training/data_reader.py#L41

Labels are initialized to 0 but are never changed during training. Shouldn't they be 1 for positive pairs and 0 for negative pairs? 

Thanks!

**Comment by amallia** [comment]
Hi @alexandres, thanks for asking.
The training input is a triplet in the form of `query, relevant, non_relevant`, so two scores are produced (one for the query-relevant and one for the query-non_relevant). The label indicates the position of the relevant document, which is always `0` since the relevant document comes always first. 

Let me know if I can help more.

**Comment by alexandres** [comment]
Understood! Thank you for the quick answer and the great work.
